#!/bin/bash
set -e
set -x
spawn()
{
  $@ 1>&2 &
  echo $!
}
ordietrying()
{
  perl -e 'alarm shift; exec @ARGV' "$@"
}

# start a few things backgrounded and concat their PIDs
PIDS=""
for x in "roslaunch operation_plushie kinect_tfs.launch $@"; do
  PIDS="$PIDS `spawn $x`"
done

# if we die, take them all with us
trap "for p in $PIDS; do kill -9 $p >& /dev/null || true; done; set +x; set +e" EXIT

# wait for the openni node's dynamic reconfigure to wake up

ordietrying 10 while ! rosrun dynamic_reconfigure dynparam list | grep -q '/driver'; do
  sleep 1
done

#if the perl alarm stops execution early
if [ $? -eq 142 ]; then
  echo "IS OPENNI RUNNING SOMEWHERE?!" 1>&2
  exit 142
fi

FQNN="`rosrun dynamic_reconfigure dynparam list | grep -q '/driver'`"

while ! rosrun dynamic_reconfigure dynparam get $FQNN | grep -q depth_registration; done
  sleep 1
done

rosrun dynamic_reconfigure dynparam set $FQNN depth_registration true

wait $PIDS

exit 0
